dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: "Xx_MASAC"
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: False
render_mode: 'human' # Choices: 'human', 'rgb_array'.
fps: 0
test_mode: False
device: "cuda:0"

agent: "MASAC"  # the learning algorithms_marl
env_name: "IEEE13"
env_id: "IEEE13"
continuous_action: True
learner: "MASAC_Learner"
policy: "Gaussian_MASAC_Policy"
representation: "Basic_Identical"  # 表示特征表示的方式。Basic_Identical 表示每个智能体使用基本的、相同的特征表示方式，即所有智能体的输入状态或观测空间的表示结构是相同的。
vectorize: "SubprocVecMultiAgentEnv"
env_seed: 1



representation_hidden_size: [64,64]  # the units for each hidden layer
actor_hidden_size: [64, 64]
critic_hidden_size: [64, 64]
activation: 'leaky_relu'
activation_action: 'sigmoid'
use_parameter_sharing: False
use_actions_mask: False

seed: 1
parallels: 1
buffer_size: 100000
batch_size: 256
learning_rate_actor: 0.01  # learning rate for actor
learning_rate_critic: 0.001  # learning rate for critic
gamma: 0.95  # discount factor
tau: 0.001  # soft update for target networks

test: False

start_noise: 1.0
end_noise: 0.01
sigma: 0.1  # random noise for continuous actions
start_training: 1000  # start training after n episodes
running_steps: 10000

alpha: 0.2
#training_frequency: 25
use_automatic_entropy_tuning: True

use_grad_clip: False
grad_clip_norm: 0.5

eval_interval: 10000
test_episode: 5

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

distributed_training: False

test_steps: 10000
log_dir: "./logs/MASAC/"
model_dir: "./models/MASAC/"


